INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1001, 'Crise nas Infinitas Terras', 10, 1000, 1000, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1002, 'Interestelar', 5, 1001, 1001, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1003, 'Harry Potter E A Pedra Filosofal', 3, 1001, 1002, CURRENT_TIMESTAMP);
